=== opencypher/openCypher/grammar/xmlschemas/ocGrammar.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2015-2020 "Neo Technology,"
    Network Engine for Objects in Lund AB [http://neotechnology.com]

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Attribution Notice under the terms of the Apache License 2.0

    This work was created by the collective efforts of the openCypher community.
    Without limiting the terms of Section 6, any Derivative Work that is not
    approved by the public consensus process of the openCypher Implementers Group
    should not be described as “Cypher” (and Cypher® is a registered trademark of
    Neo4j Inc.) or as "openCypher". Extensions by implementers or prototypes or
    proposals for change that have been documented or implemented should only be
    described as "implementation extensions to Cypher" or as "proposed changes to
    Cypher that are not yet approved by the openCypher community".

-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://opencypher.org/grammar"
	xmlns="http://opencypher.org/grammar"
	xmlns:rr="http://opencypher.org/railroad"
	xmlns:oc="http://opencypher.org/opencypher"
	xmlns:scope="http://opencypher.org/scope"
	xmlns:ast="http://opencypher.org/syntaxtree"
	elementFormDefault="qualified">

	<!-- the separately defined attributes are in different namespaces so have 
		to be in their own xsd files -->
	<xsd:import namespace="http://opencypher.org/railroad"
		schemaLocation="ocRailRoad.xsd" />

	<xsd:import namespace="http://opencypher.org/opencypher"
		schemaLocation="ocLegacy.xsd" />

	<xsd:import namespace="http://opencypher.org/scope"
		schemaLocation="ocScope.xsd" />

	<xsd:import namespace="http://opencypher.org/syntaxtree"
		schemaLocation="ocSyntaxTree.xsd" />

	<!-- the global element -->
	<xsd:element name="grammar" type="Grammar" />

	<!--  the types -->
	<xsd:complexType name="Grammar">
		<xsd:sequence>
			<xsd:choice maxOccurs="unbounded">
				<xsd:element name="vocabulary" type="Vocabulary" />
				<xsd:element name="production" type="Production" />
			</xsd:choice>
		</xsd:sequence>
		<xsd:attribute name="language" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="Vocabulary">
		<xsd:attribute name="file" type="xsd:string"/>
	</xsd:complexType>

	<!-- Production is like Sequence but has an extra element at the beginning, so
		copy-and-paste rather than extend  -->
	<xsd:complexType name="Production" mixed="true">
		<xsd:sequence>
			<xsd:element name="description" type="xsd:string"
				minOccurs="0" />
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="alt" type="Sequence"/>
				<xsd:element name="seq" type="Sequence"/>
				<xsd:element name="literal" type="Literal"/>
				<xsd:element name="character" type="Character"/>
				<xsd:element name="non-terminal" type="Non-terminal"/>
				<xsd:element name="opt" type="Sequence"/>
				<xsd:element name="repeat" type="Repeat"/>
			</xsd:choice>
		</xsd:sequence>

		<xsd:attribute name="name" type="xsd:string"/>
		<xsd:attribute ref="rr:inline"/>
		<xsd:attribute ref="rr:skip"/>
		<xsd:attribute ref="oc:legacy"/>
		<xsd:attribute ref="scope:rule"/>
		<xsd:attribute ref="oc:lexer"/>

	</xsd:complexType>

	<xsd:complexType name="Sequence" mixed="true">
		<xsd:sequence>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="alt" type="Sequence"/>
				<xsd:element name="seq" type="Sequence"/>
				<xsd:element name="literal" type="Literal"/>
				<xsd:element name="character" type="Character"/>
				<xsd:element name="non-terminal" type="Non-terminal"/>
				<xsd:element name="opt" type="Sequence"/>
				<xsd:element name="repeat" type="Repeat"/>
			</xsd:choice>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Repeat">
		<xsd:complexContent>
			<xsd:extension base="Sequence">
				<xsd:attribute name="min" type="xsd:int" default="0"/>
				<xsd:attribute name="max" type="xsd:int"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="Non-terminal">
		<xsd:attribute name="ref" type="xsd:string"/>
		<xsd:attribute ref="rr:title"/>
		<xsd:attribute ref="ast:entry"/>
	</xsd:complexType>

	<xsd:complexType name="Literal">
		<xsd:attribute name="case-sensitive" type="xsd:boolean"
			default="true"/>
		<xsd:attribute name="value" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="Character">
		<xsd:sequence>
			<xsd:element name="except" type="Except"
				maxOccurs="unbounded" minOccurs="0"/>
		</xsd:sequence>
		<xsd:attribute name="set" type="xsd:string"/>
	</xsd:complexType>


	<xsd:complexType name="Except">
		<xsd:attribute name="literal" type="xsd:string"/>
		<xsd:attribute name="codePoint" type="xsd:int"/>
		<xsd:attribute name="set" type="xsd:string"/>
	</xsd:complexType>




</xsd:schema>

=== opencypher/openCypher/grammar_info/grammar/pre-parser.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2015-2023 "Neo Technology,"
    Network Engine for Objects in Lund AB [http://neotechnology.com]

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Attribution Notice under the terms of the Apache License 2.0

    This work was created by the collective efforts of the openCypher community.
    Without limiting the terms of Section 6, any Derivative Work that is not
    approved by the public consensus process of the openCypher Implementers Group
    should not be described as “Cypher” (and Cypher® is a registered trademark of
    Neo4j Inc.) or as "openCypher". Extensions by implementers or prototypes or
    proposals for change that have been documented or implemented should only be
    described as "implementation extensions to Cypher" or as "proposed changes to
    Cypher that are not yet approved by the openCypher community".

-->
<!DOCTYPE grammar [
  <!ENTITY WS "<opt><non-terminal ref='SP'/></opt>">
  <!ENTITY SP "<non-terminal ref='SP'/>">
]>
<grammar language="Cypher Pre-Parser"
  xmlns="http://opencypher.org/grammar"
  xmlns:rr="http://opencypher.org/railroad"
  xmlns:oc="http://opencypher.org/opencypher"
  xmlns:ast="http://opencypher.org/syntaxtree"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://opencypher.org/grammar xmlschemas/ocGrammar.xsd "
  >

  <!-- / PRE-PARSER \ -->

  <production name="QueryOptions" oc:legacy="true">
    <repeat><non-terminal ref="AnyCypherOption"/> &WS;</repeat>
  </production>

  <production name="AnyCypherOption" rr:inline="true" oc:legacy="true">
    <alt>
      <non-terminal ref="CypherOption"/>
      <non-terminal ref="Explain"/>
      <non-terminal ref="Profile"/>
    </alt>
  </production>

  <production name="CypherOption" rr:inline="true" oc:legacy="true">
    CYPHER
    <opt>&SP;<non-terminal ref="VersionNumber"/></opt>
    <repeat>&SP;<non-terminal ref="ConfigurationOption"/></repeat>
  </production>

  <production name="VersionNumber" rr:inline="true" oc:legacy="true">
    <non-terminal ref="RegularDecimalReal"/>
  </production>

  <production name="Explain" rr:inline="true" oc:legacy="true">EXPLAIN</production>
  <production name="Profile" rr:inline="true" oc:legacy="true">PROFILE</production>

  <production name="ConfigurationOption" rr:inline="true" oc:legacy="true">
    <non-terminal ref="SymbolicName" ast:entry="key"/>
    &WS; = &WS;
    <non-terminal ref="SymbolicName" ast:entry="value"/>
  </production>

  <!-- \ PRE-PARSER / -->

  <vocabulary file="basic-grammar.xml"/>

</grammar>

=== opencypher/openCypher/grammar/commands.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2015-2023 "Neo Technology,"
    Network Engine for Objects in Lund AB [http://neotechnology.com]

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Attribution Notice under the terms of the Apache License 2.0

    This work was created by the collective efforts of the openCypher community.
    Without limiting the terms of Section 6, any Derivative Work that is not
    approved by the public consensus process of the openCypher Implementers Group
    should not be described as “Cypher” (and Cypher® is a registered trademark of
    Neo4j Inc.) or as "openCypher". Extensions by implementers or prototypes or
    proposals for change that have been documented or implemented should only be
    described as "implementation extensions to Cypher" or as "proposed changes to
    Cypher that are not yet approved by the openCypher community".

-->
<!DOCTYPE grammar [
  <!ENTITY WS "<opt><non-terminal ref='SP'/></opt>">
  <!ENTITY SP "<non-terminal ref='SP'/>">
  <!ENTITY var "<non-terminal ref='Variable'/>">
  <!ENTITY node "(&WS;)">
  <!ENTITY dash "<non-terminal ref='Dash' rr:title='-'/>">
  <!ENTITY larrow "<non-terminal ref='LeftArrowHead' rr:title='&lt;'/>&dash;">
  <!ENTITY rarrow "&dash;<non-terminal ref='RightArrowHead' rr:title='&gt;'/>">
  <!ENTITY label "<non-terminal ref='NodeLabel'/>">
  <!ENTITY type "<non-terminal ref='RelType'/>">
]>
<grammar language="Command"
  xmlns="http://opencypher.org/grammar"
  xmlns:rr="http://opencypher.org/railroad"
  xmlns:oc="http://opencypher.org/opencypher"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://opencypher.org/grammar xmlschemas/ocGrammar.xsd "
  >

  <production name="Command" rr:inline="true">
    <alt>
      <non-terminal ref="CreateIndex"/>
      <non-terminal ref="DropIndex"/>

      <non-terminal ref="CreateUniqueConstraint"/>
      <non-terminal ref="DropUniqueConstraint"/>

      <non-terminal ref="CreateNodePropertyExistenceConstraint"/>
      <non-terminal ref="DropNodePropertyExistenceConstraint"/>

      <non-terminal ref="CreateRelationshipPropertyExistenceConstraint"/>
      <non-terminal ref="DropRelationshipPropertyExistenceConstraint"/>

      <non-terminal ref="CreateConstraint"/>
      <non-terminal ref="DropConstraint"/>
    </alt>
  </production>

  <!-- / NEW CONSTRAINT SYNTAX \ -->

  <production name="DropConstraint">
    DROP &SP; CONSTRAINT &SP; <non-terminal ref="SymbolicName"/>
  </production>

  <production name="CreateConstraint">
    CREATE &SP; CONSTRAINT &SP; <non-terminal ref="SymbolicName"/> &SP;
    FOR &SP; <non-terminal ref="Pattern"/> &SP;
    REQUIRE &SP; <non-terminal ref="ConstraintPredicate"/>
  </production>

  <production name="ConstraintPredicate">
    <alt>
      <non-terminal ref="Expression"/>
      <non-terminal ref="Unique"/>
      <non-terminal ref="NodeKey"/>
    </alt>
  </production>

  <production name="Unique">
    <non-terminal ref="GroupedPropertyExpression"/> &SP; IS &SP; UNIQUE
  </production>

  <production name="NodeKey">
    <non-terminal ref="GroupedPropertyExpression"/> &SP; IS &SP; NODE &SP; KEY
  </production>

  <production name="GroupedPropertyExpression">
    <alt>
      <non-terminal ref="PropertyExpression"/>
      <seq>
        ( &WS; <non-terminal ref="PropertyExpression"/>
        <repeat>&WS; , &WS; <non-terminal ref="PropertyExpression"/></repeat>
        &WS; )
      </seq>
    </alt>
  </production>

  <!-- / LEGACY COMMANDS \ -->

  <production name="CreateUniqueConstraint" rr:inline="true" oc:legacy="true">
    CREATE &SP; <non-terminal ref="UniqueConstraint"/>
  </production>

  <production name="CreateNodePropertyExistenceConstraint" rr:inline="true" oc:legacy="true">
    CREATE &SP; <non-terminal ref="NodePropertyExistenceConstraint"/>
  </production>

  <production name="CreateRelationshipPropertyExistenceConstraint" rr:inline="true" oc:legacy="true">
    CREATE &SP; <non-terminal ref="RelationshipPropertyExistenceConstraint"/>
  </production>

  <production name="CreateIndex" rr:inline="true" oc:legacy="true">
    CREATE &SP; <non-terminal ref="Index"/>
  </production>

  <production name="DropUniqueConstraint" rr:inline="true" oc:legacy="true">
    DROP &SP; <non-terminal ref="UniqueConstraint"/>
  </production>

  <production name="DropNodePropertyExistenceConstraint" rr:inline="true" oc:legacy="true">
    DROP &SP; <non-terminal ref="NodePropertyExistenceConstraint"/>
  </production>

  <production name="DropRelationshipPropertyExistenceConstraint" rr:inline="true" oc:legacy="true">
    DROP &SP; <non-terminal ref="RelationshipPropertyExistenceConstraint"/>
  </production>

  <production name="DropIndex" rr:inline="true" oc:legacy="true">
    DROP &SP; <non-terminal ref="Index"/>
  </production>

  <production name="Index" oc:legacy="true">
    INDEX &SP; ON &WS; &label; (<non-terminal ref="PropertyKeyName"/>)
  </production>


  <production name="UniqueConstraint" oc:legacy="true">
    CONSTRAINT &SP; ON &WS; ( &var; &label; ) &WS;
    ASSERT &SP; <non-terminal ref="PropertyExpression"/> &SP; IS &SP; UNIQUE
  </production>

  <production name="NodePropertyExistenceConstraint" oc:legacy="true">
    CONSTRAINT &SP; ON &WS; ( &var; &label; ) &WS;
    ASSERT &SP; EXISTS &WS; ( <non-terminal ref="PropertyExpression"/> )
  </production>

  <production name="RelationshipPropertyExistenceConstraint" oc:legacy="true">
    CONSTRAINT &SP; ON &WS; <non-terminal ref="RelationshipPatternSyntax"/> &WS;
    ASSERT &SP; EXISTS &WS; ( <non-terminal ref="PropertyExpression"/> )
  </production>

  <production name="RelationshipPatternSyntax" oc:legacy="true">
    <alt>
      <seq>&node;&dash;[&var;&type;]&dash;&node;</seq>
      <seq>&node;&dash;[&var;&type;]&rarrow;&node;</seq>
      <seq>&node;&larrow;[&var;&type;]&dash;&node;</seq>
    </alt>
  </production>

  <!-- \ COMMANDS / -->

  <vocabulary file="basic-grammar.xml"/>

</grammar>

=== opencypher/openCypher/grammar_info/grammar/start.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2015-2023 "Neo Technology,"
    Network Engine for Objects in Lund AB [http://neotechnology.com]

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Attribution Notice under the terms of the Apache License 2.0

    This work was created by the collective efforts of the openCypher community.
    Without limiting the terms of Section 6, any Derivative Work that is not
    approved by the public consensus process of the openCypher Implementers Group
    should not be described as “Cypher” (and Cypher® is a registered trademark of
    Neo4j Inc.) or as "openCypher". Extensions by implementers or prototypes or
    proposals for change that have been documented or implemented should only be
    described as "implementation extensions to Cypher" or as "proposed changes to
    Cypher that are not yet approved by the openCypher community".

-->
<!DOCTYPE grammar [
  <!ENTITY WS "<opt><non-terminal ref='SP'/></opt>">
  <!ENTITY SP "<non-terminal ref='SP'/>">
  <!ENTITY var "<non-terminal ref='Variable'/>">
]>
<grammar language="Cypher Start Clause"
  xmlns="http://opencypher.org/grammar"
  xmlns:rr="http://opencypher.org/railroad"
  xmlns:oc="http://opencypher.org/opencypher"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://opencypher.org/grammar xmlschemas/ocGrammar.xsd "
  >

  <!-- / START \ -->

  <production name="Start" oc:legacy="true">
    START &SP;
    <non-terminal ref="StartPoint"/>
    <repeat>&WS;,&WS;<non-terminal ref="StartPoint"/></repeat>
    <opt><non-terminal ref="Where"/></opt>
  </production>

  <production name="StartPoint" rr:inline="true" oc:legacy="true">
    &var; &WS; = &WS; <non-terminal ref="Lookup"/>
  </production>

  <production name="Lookup" rr:inline="true" oc:legacy="true">
    <alt>
      <non-terminal ref="NodeLookup"/>
      <non-terminal ref="RelationshipLookup"/>
    </alt>
  </production>

  <production name="NodeLookup" rr:inline="true" oc:legacy="true">
    NODE &WS;
    <alt>
      <non-terminal ref="IdentifiedIndexLookup"/>
      <non-terminal ref="IndexQuery"/>
      <non-terminal ref="IdLookup"/>
    </alt>
  </production>

  <production name="RelationshipLookup" rr:inline="true" oc:legacy="true">
    <alt>RELATIONSHIP REL</alt>
    <alt>
      <non-terminal ref="IdentifiedIndexLookup"/>
      <non-terminal ref="IndexQuery"/>
      <non-terminal ref="IdLookup"/>
    </alt>
  </production>

  <production name="IdentifiedIndexLookup" oc:legacy="true">
    : <non-terminal ref="SymbolicName" rr:title="index name"/>
    ( <non-terminal ref="SymbolicName" rr:title="property key"/> =
    <alt>
      <non-terminal ref="StringLiteral"/>
      <non-terminal ref="LegacyParameter"/>
    </alt>)
  </production>

  <production name="IndexQuery" oc:legacy="true">
    : <non-terminal ref="SymbolicName" rr:title="index name"/>
    (<alt>
      <non-terminal ref="StringLiteral"/>
      <non-terminal ref="LegacyParameter"/>
    </alt>)
  </production>

  <production name="IdLookup" oc:legacy="true">
    (<alt>
      <non-terminal ref="LiteralIds"/>
      <non-terminal ref="LegacyParameter"/>
      *
    </alt>)
  </production>

  <production name="LiteralIds" rr:inline="true" oc:legacy="true">
    <non-terminal ref="IntegerLiteral"/>
    <repeat>
      &WS;,&WS;<non-terminal ref="IntegerLiteral"/>
    </repeat>
  </production>

  <!-- \ START / -->

  <vocabulary file="basic-grammar.xml"/>

</grammar>
